version: '3'
services:
  taskmasterdb:
    image: mongo
    container_name: taskmasterdb
    ports:
      - 27018:27017
  web:
    image: ${DOCKER_REGISTRY-}taskmaster
    build:
      context: .
      dockerfile: ./TaskMater.Web/Dockerfile
    ports:
      - 5050:8080
      - 5051:8081
    environment:
     ASPNETCORE_ENVIRONMENT: Development
     MongoOption:ConnectionString: "mongodb://taskmasterdb:27017"
    depends_on:
       - taskmasterdb